### PR TITLE
fix: logic around findLocally and findDealer

### LINKED ISSUE #169: [pdp] Find locally displayed instead of "Add to Cart"

### PR DESCRIPTION
**Pull request by dylandepass**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #169

Test URLs:
- Before: https://main--vitamix--aemsites.aem.network/
- After: https://fix-find-dealer--vitamix--aemsites.aem.network/

### CODE REVIEW

File: blocks/pdp/add-to-cart.js [hunk 1]
```diff
@@ -75,16 +75,17 @@ function toggleFixedAddToCart(container) {
  */
 export default function renderAddToCart(block, custom) {
   // extract config options from custom object
-  const { findLocally, findDealer, commercial } = custom;
```
Comment (dylandepass) [inline blocks/pdp/add-to-cart.js:78]: We exclude commercial products entirely right now, so `commercial` will always be undefined.

**Review by fkakatie — APPROVED** [review]
